<!--
Codes Generated By VForm:
https://www.vform666.com
-->

<template>
  <el-form
    ref="vForm"
    :model="formData"
    :rules="rules"
    label-position="left"
    label-width="150px"
    size="medium"
    @submit.native.prevent
  >
    <div class="static-content-item">
      <div>多列表单</div>
    </div>
    <div class="static-content-item">
      <el-divider direction="horizontal" />
    </div>
    <el-row>
      <el-col :span="12" class="grid-cell">
        <el-form-item label="信用证编号" prop="input12931" class="required label-right-align">
          <el-input v-model="formData.input12931" type="text" clearable :show-word-limit="true" />
        </el-form-item>
      </el-col>
      <el-col :span="12" class="grid-cell">
        <el-form-item label="提货担保次数" prop="input23031" class="required label-right-align">
          <el-input v-model="formData.input23031" type="text" clearable :show-word-limit="true" />
        </el-form-item>
      </el-col>
    </el-row>
    <el-row>
      <el-col :span="12" class="grid-cell">
        <el-form-item label="开证申请人" prop="textarea21654" class="required label-right-align">
          <el-input v-model="formData.textarea21654" type="textarea" rows="3" :show-word-limit="true" />
        </el-form-item>
      </el-col>
      <el-col :span="12" class="grid-cell">
        <el-form-item label="发货人" prop="textarea92807" class="required label-right-align">
          <el-input v-model="formData.textarea92807" type="textarea" rows="3" :show-word-limit="true" />
        </el-form-item>
      </el-col>
    </el-row>
    <el-row>
      <el-col :span="12" class="grid-cell">
        <el-form-item label="提货担保申请人" prop="textarea69514" class="required label-right-align">
          <el-input v-model="formData.textarea69514" type="textarea" rows="3" :show-word-limit="true" />
        </el-form-item>
      </el-col>
      <el-col :span="12" class="grid-cell">
        <el-form-item label="收货人" prop="textarea52899" class="required label-right-align">
          <el-input v-model="formData.textarea52899" type="textarea" rows="3" :show-word-limit="true" />
        </el-form-item>
      </el-col>
    </el-row>
    <el-row>
      <el-col :span="12" class="grid-cell">
        <el-form-item label="select" prop="select14637" class="label-right-align">
          <el-select
            v-model="formData.select14637"
            class="full-width-input"
            clearable
            filterable
            allow-create
            default-first-option
            automatic-dropdown
            remote
          >
            <el-option
              v-for="(item, index) in select14637Options"
              :key="index"
              :label="item.value"
              :value="item.value"
              :disabled="item.disabled"
            />
          </el-select>
        </el-form-item>
        <el-form-item label="开证金额" prop="input24686" class="required label-right-align">
          <el-input v-model="formData.input24686" type="text" clearable :show-word-limit="true" />
        </el-form-item>
      </el-col>
      <el-col :span="12" class="grid-cell">
        <el-form-item label="提货担保金额" prop="input60006" class="required label-right-align">
          <el-input v-model="formData.input60006" type="text" clearable :show-word-limit="true" />
        </el-form-item>
      </el-col>
    </el-row>
    <el-row>
      <el-col :span="12" class="grid-cell">
        <el-form-item label="船运公司名址" prop="textarea72706" class="label-right-align">
          <el-input v-model="formData.textarea72706" type="textarea" rows="3" />
        </el-form-item>
      </el-col>
      <el-col :span="12" class="grid-cell">
        <el-form-item label="提货担保日期" prop="date29811" class="label-right-align">
          <el-date-picker
            v-model="formData.date29811"
            type="date"
            class="full-width-input"
            format="yyyy-MM-dd"
            value-format="yyyy-MM-dd"
            clearable
          />
        </el-form-item>
      </el-col>
    </el-row>
    <div class="static-content-item">
      <el-divider direction="horizontal" />
    </div>
    <el-row>
      <el-col :span="12" class="grid-cell">
        <el-form-item label="起运港" prop="input87679" class="label-right-align">
          <el-input v-model="formData.input87679" type="text" clearable />
        </el-form-item>
      </el-col>
      <el-col :span="12" class="grid-cell">
        <el-form-item label="担保到期日" prop="date100685" class="label-right-align">
          <el-date-picker
            v-model="formData.date100685"
            type="date"
            class="full-width-input"
            format="yyyy-MM-dd"
            value-format="yyyy-MM-dd"
            clearable
          />
        </el-form-item>
      </el-col>
    </el-row>
    <el-row>
      <el-col :span="12" class="grid-cell">
        <el-form-item label="发票号码" prop="input76133" class="label-right-align">
          <el-input v-model="formData.input76133" type="text" clearable />
        </el-form-item>
      </el-col>
      <el-col :span="12" class="grid-cell">
        <el-form-item label="币种" prop="select47791" class="label-right-align">
          <el-select v-model="formData.select47791" class="full-width-input" clearable>
            <el-option
              v-for="(item, index) in select47791Options"
              :key="index"
              :label="item.value"
              :value="item.value"
              :disabled="item.disabled"
            />
          </el-select>
        </el-form-item>
        <el-form-item label="发票金额" prop="input35543" class="label-right-align">
          <el-input v-model="formData.input35543" type="text" clearable />
        </el-form-item>
      </el-col>
    </el-row>
    <div class="static-content-item">
      <el-alert
        title="Good things are coming..."
        type="info"
        :closable="true"
        :center="true"
        :show-icon="false"
        effect="light"
      />
    </div>
    <el-row>
      <el-col :span="12" class="grid-cell">
        <el-form-item label="卸货港" prop="input55897" class="label-right-align">
          <el-input v-model="formData.input55897" type="text" clearable />
        </el-form-item>
      </el-col>
      <el-col :span="12" class="grid-cell">
        <el-form-item label="装船日期" prop="date57530" class="label-right-align">
          <el-date-picker
            v-model="formData.date57530"
            type="date"
            class="full-width-input"
            format="yyyy-MM-dd"
            value-format="yyyy-MM-dd"
            clearable
          />
        </el-form-item>
      </el-col>
    </el-row>
    <el-row>
      <el-col :span="12" class="grid-cell">
        <el-form-item label="提单号码" prop="input117601" class="label-right-align">
          <el-input v-model="formData.input117601" type="text" clearable />
        </el-form-item>
      </el-col>
      <el-col :span="12" class="grid-cell">
        <el-form-item label="hscode" prop="select42048" class="label-right-align">
          <el-select v-model="formData.select42048" class="full-width-input" clearable>
            <el-option
              v-for="(item, index) in select42048Options"
              :key="index"
              :label="item.value"
              :value="item.value"
              :disabled="item.disabled"
            />
          </el-select>
        </el-form-item>
      </el-col>
    </el-row>
    <el-row>
      <el-col :span="12" class="grid-cell">
        <el-form-item label="船运公司是否国外" prop="checkbox63174" class="required label-right-align">
          <el-checkbox-group v-model="formData.checkbox63174">
            <el-checkbox
              v-for="(item, index) in checkbox63174Options"
              :key="index"
              :label="item.value"
              :disabled="item.disabled"
              style="{display: inline}"
            >{{ item.label }}</el-checkbox>
          </el-checkbox-group>
        </el-form-item>
      </el-col>
      <el-col :span="12" class="grid-cell">
        <el-form-item label="到港通知书编号" prop="input78584" class="required label-right-align">
          <el-input v-model="formData.input78584" type="text" clearable />
        </el-form-item>
      </el-col>
    </el-row>
    <div class="static-content-item">
      <el-divider direction="horizontal" />
    </div>
    <el-row>
      <el-col :span="12" class="grid-cell">
        <el-form-item label="货物名称" prop="input113997" class="label-right-align">
          <el-input v-model="formData.input113997" type="text" clearable />
        </el-form-item>
      </el-col>
      <el-col :span="12" class="grid-cell">
        <el-form-item label="船名、航次" prop="input16468" class="label-right-align">
          <el-input v-model="formData.input16468" type="text" clearable />
        </el-form-item>
      </el-col>
    </el-row>
    <el-row>
      <el-col :span="12" class="grid-cell">
        <el-form-item label="唛头" prop="textarea18391" class="label-right-align">
          <el-input v-model="formData.textarea18391" type="textarea" rows="3" />
        </el-form-item>
      </el-col>
      <el-col :span="12" class="grid-cell">
        <el-form-item label="包装" prop="textarea35953" class="label-right-align">
          <el-input v-model="formData.textarea35953" type="textarea" rows="3" />
        </el-form-item>
      </el-col>
    </el-row>
    <el-row>
      <el-col :span="12" class="grid-cell">
        <el-form-item label="货物件数" prop="input25992" class="label-right-align">
          <el-input v-model="formData.input25992" type="text" clearable />
        </el-form-item>
      </el-col>
      <el-col :span="12" class="grid-cell">
        <el-form-item label="装箱单号" prop="input91134" class="label-right-align">
          <el-input v-model="formData.input91134" type="text" clearable />
        </el-form-item>
      </el-col>
    </el-row>
    <el-row>
      <el-col :span="24" class="grid-cell" />
    </el-row>
  </el-form>

</template>

<script>
export default {
  components: {},
  props: {},
  data() {
    return {
      formData: {
        input12931: '',
        input23031: '',
        textarea21654: '',
        textarea92807: '',
        textarea69514: '',
        textarea52899: '',
        select14637: '',
        input24686: '',
        input60006: '',
        textarea72706: '',
        date29811: null,
        input87679: '',
        date100685: null,
        input76133: '',
        select47791: '',
        input35543: '',
        input55897: '',
        date57530: null,
        input117601: '',
        select42048: '',
        checkbox63174: [1],
        input78584: '',
        input113997: '',
        input16468: '',
        textarea18391: '',
        textarea35953: '',
        input25992: '',
        input91134: ''
      },
      rules: {
        input12931: [{
          required: true,
          message: '字段值不可为空'
        }],
        input23031: [{
          required: true,
          message: '字段值不可为空'
        }],
        textarea21654: [{
          required: true,
          message: '字段值不可为空'
        }],
        textarea92807: [{
          required: true,
          message: '字段值不可为空'
        }],
        textarea69514: [{
          required: true,
          message: '字段值不可为空'
        }],
        textarea52899: [{
          required: true,
          message: '字段值不可为空'
        }],
        input24686: [{
          required: true,
          message: '字段值不可为空'
        }],
        input60006: [{
          required: true,
          message: '字段值不可为空'
        }, {
          pattern: /^\d+(\.\d+)?$/,
          trigger: ['blur', 'change'],
          message: ''
        }],
        input76133: [{
          pattern: /^\d+(\.\d+)?$/,
          trigger: ['blur', 'change'],
          message: ''
        }],
        checkbox63174: [{
          required: true,
          message: '字段值不可为空'
        }],
        input78584: [{
          required: true,
          message: '字段值不可为空'
        }]
      },
      select14637Options: [{
        'label': 'select 1',
        'value': 1
      }, {
        'label': 'select 2',
        'value': 2
      }, {
        'label': 'select 3',
        'value': 3
      }],
      select47791Options: [{
        'label': 'select 1',
        'value': 1
      }, {
        'label': 'select 2',
        'value': 2
      }, {
        'label': 'select 3',
        'value': 3
      }],
      select42048Options: [{
        'label': 'select 1',
        'value': 1
      }, {
        'label': 'select 2',
        'value': 2
      }, {
        'label': 'select 3',
        'value': 3
      }],
      checkbox63174Options: [{
        'label': '',
        'value': 1
      }]
    }
  },
  computed: {},
  watch: {},
  created() {},
  mounted() {},
  methods: {
    submitForm() {
      this.$refs['vForm'].validate(valid => {
        if (!valid) return
        // TODO: 提交表单
      })
    },
    resetForm() {
      this.$refs['vForm'].resetFields()
    }
  }
}

</script>

<style lang="scss">
.el-input-number.full-width-input,
.el-cascader.full-width-input {
  width: 100% !important;
}

.el-form-item--medium {
  .el-radio {
    line-height: 36px !important;
  }

  .el-rate {
    margin-top: 8px;
  }
}

.el-form-item--small {
  .el-radio {
    line-height: 32px !important;
  }

  .el-rate {
    margin-top: 6px;
  }
}

.el-form-item--mini {
  .el-radio {
    line-height: 28px !important;
  }

  .el-rate {
    margin-top: 4px;
  }
}

.clear-fix:before,
.clear-fix:after {
  display: table;
  content: "";
}

.clear-fix:after {
  clear: both;
}

.float-right {
  float: right;
}

</style>

<style lang="scss" scoped>
div.table-container {
  table.table-layout {
    width: 100%;
    table-layout: fixed;
    border-collapse: collapse;

    td.table-cell {
      display: table-cell;
      height: 36px;
      border: 1px solid #e1e2e3;
    }
  }
}

div.tab-container {}

.label-left-align ::v-deep .el-form-item__label {
  text-align: left;
}

.label-center-align ::v-deep .el-form-item__label {
  text-align: center;
}

.label-right-align ::v-deep .el-form-item__label {
  text-align: right;
}

.custom-label {}

.static-content-item {
  min-height: 20px;
  display: flex;
  align-items: center;

  ::v-deep .el-divider--horizontal {
    margin: 0;
  }
}

</style>
