<!--
Codes Generated By VForm:
https://www.vform666.com
-->

<template>
  <el-form
    ref="vForm"
    :model="formData"
    :rules="rules"
    label-position="left"
    label-width="80px"
    size="medium"
    @submit.native.prevent
  >
    <el-row>
      <el-col :span="8" class="grid-cell">
        <el-form-item label="select" prop="select58555">
          <el-select v-model="formData.select58555" class="full-width-input" clearable>
            <el-option
              v-for="(item, index) in select58555Options"
              :key="index"
              :label="item.label"
              :value="item.value"
              :disabled="item.disabled"
            />
          </el-select>
        </el-form-item>
      </el-col>
      <el-col :span="8" class="grid-cell">
        <el-form-item label="select" prop="select32538">
          <el-select v-model="formData.select32538" class="full-width-input" clearable>
            <el-option
              v-for="(item, index) in select32538Options"
              :key="index"
              :label="item.label"
              :value="item.value"
              :disabled="item.disabled"
            />
          </el-select>
        </el-form-item>
      </el-col>
      <el-col :span="8" class="grid-cell">
        <el-form-item label="select" prop="select71837">
          <el-select v-model="formData.select71837" class="full-width-input" clearable>
            <el-option
              v-for="(item, index) in select71837Options"
              :key="index"
              :label="item.label"
              :value="item.value"
              :disabled="item.disabled"
            />
          </el-select>
        </el-form-item>
      </el-col>
    </el-row>
    <el-row>
      <el-col :span="8" class="grid-cell">
        <el-form-item label="date-range" prop="daterange68462">
          <el-date-picker
            v-model="formData.daterange68462"
            is-range
            type="daterange"
            class="full-width-input"
            format="yyyy-MM-dd"
            value-format="yyyy-MM-dd"
            clearable
          />
        </el-form-item>
      </el-col>
      <el-col :span="8" class="grid-cell">
        <el-form-item label="input" prop="input62265">
          <el-input v-model="formData.input62265" type="text" clearable />
        </el-form-item>
      </el-col>
      <el-col :span="8" class="grid-cell">
        <el-form-item label="input" prop="input76334">
          <el-input v-model="formData.input76334" type="text" clearable />
        </el-form-item>
      </el-col>
    </el-row>
    <el-row>
      <el-col :md="12" :sm="12" :xs="12" class="grid-cell">
        <div class="static-content-item">
          <el-button>查询</el-button>
        </div>
        <div class="static-content-item">
          <el-button>重置</el-button>
        </div>
        <div class="static-content-item">
          <el-button>功能1</el-button>
        </div>
        <div class="static-content-item">
          <el-button>功能2</el-button>
        </div>
        <div class="static-content-item">
          <el-button>功能3</el-button>
        </div>
        <div class="static-content-item">
          <el-button>功能4</el-button>
        </div>
      </el-col>
      <el-col :span="12" class="grid-cell" />
    </el-row>
    <el-row>
      <el-col :span="12" class="grid-cell" />
      <el-col :span="12" class="grid-cell">
        <div class="static-content-item">
          <el-button>新增</el-button>
        </div>
        <div class="static-content-item">
          <el-button>修改</el-button>
        </div>
        <div class="static-content-item">
          <el-button>查看</el-button>
        </div>
        <div class="static-content-item">
          <el-button type="primary">删除</el-button>
        </div>
      </el-col>
    </el-row>
  </el-form>

</template>

<script>
export default {
  components: {},
  props: {},
  data() {
    return {
      formData: {
        select58555: '',
        select32538: '',
        select71837: '',
        daterange68462: null,
        input62265: '',
        input76334: ''
      },
      rules: {},
      select58555Options: [{
        'label': 'select 1',
        'value': 1
      }, {
        'label': 'select 2',
        'value': 2
      }, {
        'label': 'select 3',
        'value': 3
      }],
      select32538Options: [{
        'label': 'select 1',
        'value': 1
      }, {
        'label': 'select 2',
        'value': 2
      }, {
        'label': 'select 3',
        'value': 3
      }],
      select71837Options: [{
        'label': 'select 1',
        'value': 1
      }, {
        'label': 'select 2',
        'value': 2
      }, {
        'label': 'select 3',
        'value': 3
      }]
    }
  },
  computed: {},
  watch: {},
  created() {},
  mounted() {},
  methods: {
    submitForm() {
      this.$refs['vForm'].validate(valid => {
        if (!valid) return
        // TODO: 提交表单
      })
    },
    resetForm() {
      this.$refs['vForm'].resetFields()
    }
  }
}

</script>

<style lang="scss">
.el-input-number.full-width-input,
.el-cascader.full-width-input {
  width: 100% !important;
}

.el-form-item--medium {
  .el-radio {
    line-height: 36px !important;
  }

  .el-rate {
    margin-top: 8px;
  }
}

.el-form-item--small {
  .el-radio {
    line-height: 32px !important;
  }

  .el-rate {
    margin-top: 6px;
  }
}

.el-form-item--mini {
  .el-radio {
    line-height: 28px !important;
  }

  .el-rate {
    margin-top: 4px;
  }
}

.clear-fix:before,
.clear-fix:after {
  display: table;
  content: "";
}

.clear-fix:after {
  clear: both;
}

.float-right {
  float: right;
}

</style>

<style lang="scss" scoped>
div.table-container {
  table.table-layout {
    width: 100%;
    table-layout: fixed;
    border-collapse: collapse;

    td.table-cell {
      display: table-cell;
      height: 36px;
      border: 1px solid #e1e2e3;
    }
  }
}

div.tab-container {}

.label-left-align ::v-deep .el-form-item__label {
  text-align: left;
}

.label-center-align ::v-deep .el-form-item__label {
  text-align: center;
}

.label-right-align ::v-deep .el-form-item__label {
  text-align: right;
}

.custom-label {}

.static-content-item {
  min-height: 20px;
  display: flex;
  align-items: center;

  ::v-deep .el-divider--horizontal {
    margin: 0;
  }
}

</style>
